AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://disable-running-resources--java-artifacts/81ff3310aa2c8156ee5b91bf5e1e751a
      Handler: example.Handler::handleRequest
      Runtime: java8
      Description: Java function
      MemorySize: 512
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambdaReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
