AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that calls the Lambda API.
Globals:
  Function:
    Environment:
      Variables:
        STOP_EC2_INSTANCES_WITH_TAG: ''
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://disable-running-resources--java-artifacts/9986065a6c18827344d1b289e6488049
      Handler: example.Handler::handleRequest
      Runtime: java8
      Description: Java function
      MemorySize: 512
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambdaReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      - AmazonEC2FullAccess
      Tracing: Active
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: SNS
            Destination:
              Ref: SnsTopic
          OnFailure:
            Type: SNS
            Destination:
              Ref: SnsTopic
  ScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Description: To fire off the disable-running-resources lambda function
      Name: disable-running-resources-lambda-schedule
      ScheduleExpression: rate(5 minutes)
      State: ENABLED
      Targets:
      - Arn:
          Fn::GetAtt:
          - LambdaFunction
          - Arn
        Id: 1
        RetryPolicy:
          MaximumRetryAttempts: 4
          MaximumEventAgeInSeconds: 400
  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: LambdaFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
  SnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: disable-running-resources-lambda-notification
      Subscription:
      - Endpoint: 12673942015
        Protocol: SMS
      - Endpoint: '{{resolve:ssm:/personal-info/email-address:1}}'
        Protocol: Email
