AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
# Parameters:
#   LambdaArn:
#     Type: String
#     Description: Provide the ARN of the Lambda Function the CloudWatch Rule will create
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/disable-running-resources-1.0-SNAPSHOT.jar
      Handler: example.Handler::handleRequest
      Runtime: java8
      Description: Java function
      MemorySize: 512
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - AmazonEC2FullAccess
      Tracing: Active
  ScheduledRule:
    Type: AWS::Events::Rule
    Properties: 
      Description: To fire off the disable-running-resources lambda function
      Name: disable-running-resources-lambda-schedule
      ScheduleExpression: cron(0 8 * * ? *)
      # ScheduleExpression: rate(1 minute)
      State: ENABLED
      Targets: 
        - Arn: 
            !GetAtt LambdaFunction.Arn
          Id: 1
          RetryPolicy:
            MaximumRetryAttempts: 4
            MaximumEventAgeInSeconds: 400
  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref "LambdaFunction"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      # SourceArn: 
      #   Fn::GetAtt: 
      #     - "ScheduledRule"
      #     - "Arn"            
  # scheduledNotification:
  #   Type: AWS::Events::Rule
  #   Properties: 
  #     Description: Reminder that instances will be stopped
  #     Name: disable-running-resources-notification-schedule
  #     # ScheduleExpression: cron(0 3 * * ? *)
  #     ScheduleExpression: rate(5 minutes)
  #     State: ENABLED
  #     Targets: 
  #       - Arn: 
  #           !GetAtt LambdaFunction.Arn
  #         Id: 2
  #         RetryPolicy:
  #           MaximumRetryAttempts: 4
  #           MaximumEventAgeInSeconds: 400
