AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
# Parameters:
#   LambdaArn:
#     Type: String
#     Description: Provide the ARN of the Lambda Function the CloudWatch Rule will create
Globals:
  Function:
    Environment:
      Variables:
        STOP_EC2_INSTANCES_WITH_TAG_NAME: ""
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/disable-running-resources-1.0-SNAPSHOT.jar
      Handler: example.Handler::handleRequest
      Runtime: java8
      Description: Java function
      MemorySize: 512
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - AmazonEC2FullAccess
      Tracing: Active
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: SNS
            Destination: !Ref SnsTopic
          OnFailure:
            Type: SNS
            Destination: !Ref SnsTopic
  ScheduledRule:
    Type: AWS::Events::Rule
    Properties: 
      Description: To fire off the disable-running-resources lambda function
      Name: disable-running-resources-lambda-schedule
      ScheduleExpression: cron(0 8 * * ? *)
      # ScheduleExpression: rate(5 minutes)
      State: ENABLED
      Targets: 
        - Arn: 
            !GetAtt LambdaFunction.Arn
          Id: 1
          RetryPolicy:
            MaximumRetryAttempts: 4
            MaximumEventAgeInSeconds: 400
  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref "LambdaFunction"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      # SourceArn: 
      #   Fn::GetAtt: 
      #     - "ScheduledRule"
      #     - "Arn"            
  SnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: disable-running-resources-lambda-notification
      Subscription:
        - Endpoint: '{{resolve:ssm:/personal-info/phone-number:1}}'
          Protocol: SMS
        - Endpoint: '{{resolve:ssm:/personal-info/email-address:1}}'
          Protocol: Email
        
