AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/disable-running-resources-1.0-SNAPSHOT.jar
      Handler: example.Handler::handleRequest
      Runtime: java8
      Description: Java function
      MemorySize: 512
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - AmazonEC2FullAccess
      Tracing: Active
  schedule:
    Type: AWS::Events::Rule
    Properties: 
      Description: To fire off the disable-running-resources lambda function
      # EventBusName: String
      # EventPattern: Json
      Name: disable-running-resources-lambda-schedule
      # RoleArn: String
      ScheduleExpression: cron(0 8 * * ? *)
      State: ENABLED
      Targets: 
        - Arn: 'arn:aws:lambda:us-east-1:297211837959:function:disable-running-resources-function-1TEXV8O88VEGK'
          Id: 1
          RetryPolicy:
            MaximumRetryAttempts: 4
            MaximumEventAgeInSeconds: 400
